### ISSUE TITLE
Fields are not shown at featured articles overview / category blog 

### ISSUE THREAD

**Issue by coolcat-creations** [joomla-projects/custom-fields#108]
#### Steps to reproduce the issue

create an category blog menu-item and link to the category of the article
#### Expected result

fields should be shown there or there should be a option to decide if they are shown in category listing or not
#### Actual result

fields are not shown

**Comment by laoneo** [comment]
The problem is that another event is triggered with the context _com_content.category_. In DPFields I have made a built in mechanism to connect contexts with each other. With the given architecture it is not possible to catch them as well. Perhaps somebody else has a clue how to fix it without doubling the event triggers.
