### ISSUE TITLE
Multiple param

### ISSUE THREAD

**Issue by brianteeman** [joomla-projects/custom-fields#30]
I would position this below the required param

**Comment by laoneo** [comment]
Can you post a screenshot what you would position where?

**Comment by brianteeman** [comment]
## Before

![before](https://cloud.githubusercontent.com/assets/1296369/14209991/4565d852-f827-11e5-853a-0234f24e5ca5.png)

## After

![after](https://cloud.githubusercontent.com/assets/1296369/14210000/498263c4-f827-11e5-9dfc-3d27373c7688.png)

**Comment by laoneo** [comment]
The problem is that the  multiple parameter is type specific while the default parameter is globally for all fields. Because of that the default value will always be between the is required and multiple field. The only solution would be to move the default field to the bottom of all fields or above is required field.

**Comment by wilsonge** [comment]
I think if you have constant things between all fields and field specific stuff then this makes sense as it is :)
