### ISSUE TITLE
Architectural issues found while checking the custom fields system

### ISSUE THREAD

**Issue by phproberto** [joomla-projects/custom-fields#88]
First of all I don't pretend to be negative. I attended JAB fields session and I saw some issues in the current system. Please take this as my try to improve things. I really appreciate all the effort here and that a company decides to contribute something that they could keep for themselves.

That said my company has its own field system and I had to deal with some issues that I see here when I was assigned there to improve the field system. I have only played with the system a couple of hours so forgive me if there is something that I missunderstood.
### 1. "This is not a CCK".

In the JAB session this was said about the current implementation. In my opinion Joomla users expect a core CCK and that's what we should give them. Releasing a field system that is not a CCK when it's something that can be done with some changes will only lead to having to fix a system after it has been released with all the complications that brings in. Please let's think big, provide big solutions and make our users very happy with the solutions we provide.

Some of the issues described here are related to the goal of integrating a core CCK system.
### 2. Fields are not plugins.

In current system fields are shipped with components. In my opinion fields should be based in plugins and that's the biggest mistake I'm seeing here. 

With field plugins:
- You have an interface that describes what a field should provide. So your system is 100% open to anybody implementing a totally different logic.
- You have a base abstract plugin class that provides most of the logic required by any field plugins (global parameters, etc.) and also a field wrapper that acts as a connector between plugin fields and JForm fields. A plugin can be created with ~150 lines of code.
- Each field takes care of validating the data being saved (with an event fired in the tables' check method).
- Each field takes care of encoding/decoding data saved in the database. So a plugin can decide to store a json string and that would be transparent for the field system. Having a layout to "prepare" the data is wrong architecturally. Data is not something to be changed in layouts.
- Plugins can also decide that they are not using DB at all if that's the case.
- Field plugins can be installed by external systems. So if my ecommerce extension provides a plugin to select a product you can use it in your component to create relationships between articles + my ecommerce products. Users doen't need to know where that new field comes from. This what really opens a new world of collaboration between `com_content` in a way that has been never possible in Joomla. A system more like WordPress.
- Fields announce themselves as available with an event (something like onGetAvailableCustomFields) so it's easy to allow to use those fields everywhere (modules, menus, etc.) which is also connected with the previous point. Extension developers can stop using `addfieldpath` because system has a better way to know which fields are available.
- Fields can be easily replaced when required. So if you want to use your own text field you only have to duplicate it adjust the logic there and disable the field I want to replace. Easy to customise anything.
- Field plugins can also adjust queries for search plugins. So if my plugin stores an id from an external system I can include a left join for a different db table.

I think it's quite obvious that growing over plugins is better.
### 3. EAV model.

EAV model (something current implementation tries to use) has some performance issues. So it's not something to decide easily. Benefits of EAV is that DB changes are easy to do and understand. I'd say that everything else is bad. Data is stored as text field so DB filtering is bad.

My company adopted supertype/subtype pattern which is more like content types concept from the UCM system. Each content type will generate a subtype on the fly for its current fields. Something like:

`#__content` (main table)

To store standard content.

`#__content_type_2` (specific content type data sharing the same primary key than main table)

To store data stored in custom fields. Each time a new field is saved that content type is modified adding a new column of the type provided by the plugin field (integer, text, datetime, etc.). So field types in database are correct. Also getting custom data for an item is easy because you only have to do a join and you get everything related to it. 

The "bad" things of subtypes are:
- While EAV only uses a couple of tables with subtypes each content type (subtype) will have its own db table so a lot of tables can be created. I think this is not really bad because at the end is more natural to have a table for an entity than having a table to store all the properties from all the entities. Sites won't probably have a lot of content types and if they do it's because the site is supposed to be big.
- Each time a field is added/removed an ALTER command is executed and that blocks the table. That does not happen with EAV. I think is better to be faster reading things than saving them because editing content types is not something you are going to do everyday and reading is an operation that will affect performance for daily visitors.
### 4. Content types.

Current system uses a main content type for articles and then the "category field" to put fields inside. In my opinion Category fields should be content types which defines them in a better way. You need a main content type like `com_content.article` which is the source content type and then the user defined content type.
### 5. Field options stored as JSON

Options should be stored in its own database table with an ordering column, params, etc. So they can grow without being tied to a predefined JSON  structure. This isn't so bad because you are never going to search for options, etc. but using a different table allows that options can also be checked on save by field plugins. So if my plugin only supports X,Y,Z options is the plugin what will take care of warning the user.
### 6. Mustache

I think this needs an higher debate because a template engine is something that our users will have to learn and will naturally replace jlayout so checking all the options is something that has to happen before shipping anything implemented. I'm ok as long as that's something decided properly seeing the pros and cons of each solution. Personally I'd prefer to use Twig.

And that's all. Again please don't take this as me blocking features from being added but me trying to see things done in the right way. 

If J4 thing is happening (not JX) I think this should be delayed until then so hopefully the UCM system can really be something that extension developers can use and maybe the base for a CCK system done in the right way.

**Comment by skelgaard** [comment]
i really like your idea and i agree... it has to be a CCK else its not gonna be what is needed for Joomla to grow on.
What i don't see in this, and what is also needed, is a way to control view/edit for both frontend/backend for this to really work and be usable.
At the current state, i only see it half usable and the "dream" i had that this could be a real replacement for stuff like k2, zoo and the likeings cannot be done with the current state, but with your suggestion it has a change of getting back into this.
Also thinking J4, this would be the way to go and as said before, why not do the work, where it can be used mostly by doing what would be best for both.

**Comment by AndyGaskell** [comment]
Just to offer my thoughts on this, I hope it may be helpful.

I've used various CCK and Extra field systems over the last few years in a wide range of use cases.

I've used, in order of frequency...
- FieldsAttatch
- K2
- DP Fields
- Self written field extensions
- jReviews

The use cases it has been with are...
- Ford dealership, used, with car specs in fields
- Tractor dealership, used, with car specs in fields
- App backend content systems, with extra context relevant info in fields
- Architecture firm, with project info in extra fields, inc lat/lon rendered as maps
- Multi publication regional business news
- Vauxhall / Opel car parts catalogue
- Disability care holiday provision, with search-able site facilities 
- Property catalogue
- Nationwide children's play facility database
- Online review and recommendation system for builders and trades people
- e-learning system for off shore energy environmental protection

...and probably a few others.

From this, my feeling is that having an addition to the existing content interface is much simpler to the end user.  So, in that sense, the lighter CCKs like FieldsAttatch and DPFields have been a better option, looking back at these projects retrospectively.

As a developer, I've found that FieldsAttatch and DP Fields have made for a shorter and more flexible development iterations.

I'd be happy to expand on this with specific examples, if that'd be helpful.

Of course, this is only my opinion and thoughts, that I humbly offer, with a view to possibly contributing this discussion.

**Comment by phproberto** [comment]
@AndyGaskell I'm not suggesting that content/fields are managed from a different place. Issue is about what's behind the current interface not about the interface itself.

**Comment by laoneo** [comment]
I think we have to be very carefully when Joomla starts to introduces functionality which is already available by extensions. Adding a CCK to the Joomla core would also increase the complexity. IMO Joomla should provide as much help as possible for extensions to easily add new functionality (as com_history or com_tags does) and not to make them obsolete. It should attract extension developers and not making them running away. If we are going to add a CCK then the extension developer would think, do they replace mine functionality with a new core feature as well?

Adding extra fields to com_fields trough plugin events is planed on a later iteration as the PR for com_fields will be already very big.

If you see some issues on the current database implementation and you think something I can do better, don't hesitate to open a pull request. As I said in my talk, I'm open for new ideas :-)

Too bad we didn't found time to discuss that on JAB.

**Comment by skelgaard** [comment]
@laoneo in the current implementation and as a not develop, try look at whats been made so far... Everything i have hear/read about J4, is making it more usable and easier to use for none developers, and the current state/implementation i can't see how this should help that objective ?

As i wrote before, a good implementation of custom fields, should implement a template control for edit/view so that edit and display can be easy controled and working.
The whole implementation as suggested here, may not be good for j3.6, but at least for j4 it should be looked into.

**Comment by laoneo** [comment]
View is made fully with JLayouts and edit is controlled by JForm/the component. So we did as much as possible.

**Comment by laoneo** [comment]
Thanks again for your thoughts on it and I hope it will be the starting point for a Joomla core CCK project. But the aim of com_fields is different. If there are some development issues found please report each of them as a single issue that we can track and fix them individually.
I'm closing this issue with the hope that it is not the last word spoken about CCK and Joomla core.

**Comment by pulsarinformatique** [comment]
Hi

We, at Pulsar, have been working with Joomla since 2007. In 2010 our projects became to grow biger and we couldn't continue to just add components above components.

So we almost decided to drop Joomla! in favor of Drupal which is cck based. However having invested on Joomla for years and with a complete team devoted to Joomla in our company, leaving Joomla! was not easy at all.

So we checked if Joomla had ccks and [we tested most of them](http://www.pulsar-informatique.com/services/agence-web-joomla/comment-creer-un-site-internet/quelle-technologie-choisir/cms-open-source/expert-cms-joomla/developpements-cck-pour-joomla/cck-seblod-pour-joomla) and decided to go on with SEBLOD.

From 2011 on almost all our developpment have been made with Joomla / Seblod and I can't miss an opportunity to present the advantage of its approach and model.

Phproberto, you are right, Joomla! users expect a full CCK, not just fields, but let me share some thought please :+1: 

1- yes fields should be plugins
2- more imporant than fields: content types! with inheritage between them. and the standard Joomla article has to be just one of these content types. The cck has to enlarge Joomla!  not replacing it.
3- yes additionnal fields should be in additional tables joined with #__content (with some special rules for shared fields among various content types)
4- but the real advantage of a cck is not the fields themselves, it's the searches / lists: This is where Seblod shines. The Joomla! lists should be able to be filtered and ordered with the additional fields of the new content types.

Look at Seblod! for me it's the best example of what should be done. This CCK not only provides additional fields, it really extends com_content and a full model of lists and searches while beeing native Joomla! article based. It also allows to extends categories, users and usergroups. You also have a native multi site feature with the Joomla! acl. However the company behind has spent a lot of resources to developp and maintain it and it would take years to do it from scratch.

My only concern with Seblod has always be the fact it's not 100% native Joomla! it's 90% native but there are holes and gaps that could barely be fixed. Most of them rely on the router limits but I've started a [long discussion](https://groups.google.com/forum/#!topic/joomla-dev-cms/pCAPIs980kk%5B126-150%5D) that started the new router Hannes has delivered. But they are other issues that can't be fixed unless we change Joomla! itself.

At the end we are facing a real philosophy issue: While Drupal grows by absorbing best extensions (CCK then VIEWS) Joomla! continue to shrink to the lightest platform allowing third party developpers to bring functionalities. 

It's true that providing a native CCK will make Joomla! compete with its own extensions providers but this may be the price to pay to get a much better and more professional tool.

Enjoyed sharing thoughts with you

Cyril

**Comment by pulsarinformatique** [comment]
And if a real complete native CCK is far too complex to achieve may be we could at least allow native Joomla lists to be filtered and ordered by the custom fields as I wrote on https://github.com/joomla-projects/joomla-cms/issues/270

thanks

cyril

**Comment by pulsarinformatique** [comment]
The discussion has been moved to https://github.com/joomla/joomla-cms/issues/11535
